### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andylibrian** [laraiba/php-quran-resource#1]
- [x] Surat Initializer
- [x] Al Quran Data
- [x] Surat Repository Factory
- [x] Ayat Repository Factory
- [x] Readme += Usage
- [x] Put Copyright of Tanzil
