### ISSUE TITLE
TODO 2

### ISSUE THREAD

**Issue by andylibrian** [laraiba/php-quran-resource#2]
- [x] Service Container
- [x] Service Factory
- [x] Test Coverage
- [x] Service Documentation
- [x] Translation
- [x] Update README : ayat id & translation
- [x] Code coverage for translation
- [ ] Extended Attributes
- [ ] API Documentation
- [ ] Sample Application & demo
